import Header from "@/components/Header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import BacktoTop from "@/components/BacktoTop/BacktoTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <BacktoTop />
      </body>
    </html>
  );
}
